import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  headerContainer: {
    height: 173,
    backgroundColor: "#7A4A9E",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: "#F2F2F2",
  },
  mainContainer: {
    flex: 1,
    backgroundColor: "#F2F2F2",
    paddingHorizontal: 24,
  },
  inputWrapper: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 35,
    position: "relative",
    top: -27,
  },
  input: {
    flex: 1,
    maxWidth: "100%",
    height: 54,
    padding: 16,
    borderWidth: 0.5,
    borderColor: "#808080",
    borderRadius: 6,
    backgroundColor: "#F2F2F2",
    fontSize: 16,
    fontWeight: "400",
    marginRight: 4,
  },
  button: {
    width: 52,
    height: 52,
    backgroundColor: "#31C667",
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  infoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  productWrapper: {
    flexDirection: "row",
  },
  finishedWrapper: {
    flexDirection: "row",
  },
  productText: {
    color: "#31C667",
    fontSize: 14,
    fontWeight: "700",
    marginRight: 8,
  },
  productNumber: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "#D9D9D9",
    fontSize: 12,
    fontWeight: "700",
    borderRadius: 50,
  },
  finishedText: {
    color: "#7A4A9E",
    fontSize: 14,
    fontWeight: "700",
    marginRight: 8,
  },
  finishedNumber: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "#D9D9D9",
    fontSize: 12,
    fontWeight: "700",
    borderRadius: 50,
  },
  emptyListContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 48,
    borderTopWidth: 1,
    borderColor: "#D9D9D9",
  },
  strongText: {
    marginTop: 16,
    color: "#808080",
    fontSize: 14,
    fontWeight: "700",
  },
  normalText: {
    color: "#808080",
    fontSize: 14,
    fontWeight: "400",
  },
});
